apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hlpl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hlpl
    app.kubernetes.io/part-of: byoc-app-outm
  name: hlpl
spec:
  rules:
  - host: hlpl-byoc-ocvf-tenant.apps.5ef05e911673389a5a6b.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: hlpl
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
