apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hlpl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hlpl
    app.kubernetes.io/part-of: byoc-app-outm
  name: hlpl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: hlpl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: hlpl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-ocvf-tenant/byoc-app-outm/hlpl@sha256:62533df8254e2bd54c1d58d71fd1b5430db6b58d5160a8af477ba0bf3647387f
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
